{
  "name": "demo",
  "corpus_fps": [
    "C:/Users/Kahsolt/Documents/Workspace/ThusSpakeDechuanSan/corpus/25381406541434.txt",
    "C:/Users/Kahsolt/Documents/Workspace/ThusSpakeDechuanSan/corpus/92081433258480.txt"
  ],
  "corpora_fp": "C:\\Users\\Kahsolt\\Documents\\Workspace\\ThusSpakeDechuanSan\\corpora\\demo.txt",
  "model_fp": "C:\\Users\\Kahsolt\\Documents\\Workspace\\ThusSpakeDechuanSan\\models\\demo.pkl"
}